package com.logicommerce.sdk.enums;

public enum MarketplaceValues {
	MARKETPLACE_ID,
	MARKETPLACE_ORDER,
	MARKETPLACE_ORDER_ID,
	MARKETPLACE_SHIPPER_ID,
	MARKETPLACE_WAREHOUSE_ID,
	MARKETPLACE_EXTERNAL_SHIPPER_ID,
	MARKETPLACE_CHANNEL_ID,
	MARKETPLACE_HEADQUARTER_ID,
	MARKETPLACE_USER_ID
}