package com.logicommerce.sdk.enums;

public enum OptionValueType {
	BOOLEAN,
	SHORT_TEXT,
	SINGLE_SELECTION,
	MULTIPLE_SELECTION,
	SINGLE_SELECTION_IMAGE,
	MULTIPLE_SELECTION_IMAGE,
	SELECTOR,
	DATE,
	LONG_TEXT,
	ATTACHMENT;
}
