package com.logicommerce.sdk.enums;

public enum SettingOrderSubstatusActionType {
	SEND_MAIL,
	CHANGE_GROUP,
	RESET_INTEGRATION,
	CREATE_INVOICE,
	SPEND_GIFT_CODES,
	RELEASE_GIFT_CODES,
	SPEND_DISCOUNTS,
	RELEASE_DISCOUNTS,
	NOTIFICATION,
	CHANGE_SHIPMENT_STATUS;
}
